# Generated by Django 2.2.1 on 2019-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='access_rights',
            field=models.CharField(blank=True, max_length=30, verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='managers',
            field=models.CharField(blank=True, max_length=30, verbose_name='Менеджеры '),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона '),
        ),
        migrations.AlterField(
            model_name='employees',
            name='work_phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Рабочий телефон '),
        ),
    ]
