# Generated by Django 2.2.1 on 2019-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190507_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='fio',
            field=models.CharField(blank=True, max_length=30, verbose_name='ФИО'),
        ),
    ]
