# Generated by Django 2.2.1 on 2019-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargostatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargostatus',
            options={'verbose_name': 'Статус груза', 'verbose_name_plural': 'Статус грузов'},
        ),
        migrations.AddField(
            model_name='cargostatus',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер груза'),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='customer_rate',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ставка клиента '),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='data_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время '),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='delta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дельта '),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='rate_carriage',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ставка заказчика '),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Статус '),
        ),
        migrations.AlterField(
            model_name='cargostatus',
            name='who_maked',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кто поставил '),
        ),
    ]
