# Generated by Django 2.2.1 on 2019-05-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargostatus', '0002_auto_20190507_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargostatus',
            options={'verbose_name': 'Груз', 'verbose_name_plural': 'Статус грузов'},
        ),
    ]
