# Generated by Django 2.2.1 on 2019-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listallcargos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'verbose_name': 'Груз', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AlterField(
            model_name='cargos',
            name='at',
            field=models.CharField(blank=True, max_length=10, verbose_name='Вес груза '),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тип груза '),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='volume',
            field=models.CharField(blank=True, max_length=10, verbose_name='Объём груза '),
        ),
    ]
